### ISSUE TITLE
有没有被Telegraph封的风险？

### ISSUE THREAD

**Issue by danaoairuike** [missuo/Telegraph-Image-Hosting#4]
毕竟是白嫖Telegraph

**Comment by missuo** [comment]
甚至都没有登录。。怎么封。。。

**Comment by missuo** [comment]
最坏的结果就是你上传的图片被删了。所以很重要的图片请不要使用这种方式。

**Comment by danaoairuike** [comment]
> 最坏的结果就是你上传的图片被删了。所以很重要的图片请不要使用这种方式。

有人反映过图片被删么

**Comment by missuo** [comment]
> > 最坏的结果就是你上传的图片被删了。所以很重要的图片请不要使用这种方式。
> 
> 有人反映过图片被删么

What I'm trying to say is that every country has its own laws, even in the free USA, not all photos can be distributed, for example child pornography is not allowed in the USA. So whether or not a photo has been deleted depends entirely on the content of your photo, however whether or not anyone has reported that it has been deleted it's not very important and has no reference value because you will never upload the same photo. 

**I think it's more important to please follow the laws of the country.**
